### ISSUE TITLE
Issue with ngOptions

### ISSUE THREAD

**Issue by gsklee** [gsklee/ngStorage#21]
https://twitter.com/msthmnd/status/383966861659877380

Gotta find some time and check into this issue.

**Comment by gpltaylor** [comment]
I am having issues with ngOption. 

When using the Select/ngOption the selected item is not being selected within the select list. You can see from the example below that the title is being stored into the session and displayed into the new. However the model for the select is not updating the "Selected" within the select option.. Sorry if this does not make sense.

I have got round this by finding the "real" title and re-assigning the titles[n] item manually. This is a little clunky.

Simple plnkr here:
http://plnkr.co/edit/GAjKF0UoOxj2hNkSbdFt?p=preview

**Comment by shazzababs** [comment]
I know this is really old, but I had issues with ng-options and the initial ng-model value not being set (as in your plunker).
After much googling I discovered the issue was that ng-model sets by reference, so if you are storing a reference in sessionStorage, you need to re-point it at the new instance of the array so that ng-model can actually find the value.

Adding this code to your controller initialisation should fix the issue,and mean that you can just us sessionStorage (without the secondary scope variables) for your select:

```
// Repoint the title value to our array as ng-model links by reference
    for (var index = 0; index < $scope.titles.length; index++)
    {
        if ($scope.titles[index].id == $scope.$storage.title.id)
        {
            $scope.$storage.title = $scope.titles[index];
        }
    }
```
