### ISSUE TITLE
Can it be injected into another provider?

### ISSUE THREAD

**Issue by yleemj** [gsklee/ngStorage#70]
app.provider('Item', ['$localStorage',
    function($localStorage) {
................
}])

seems not working, cannot find the $localStorage provider

**Comment by GabrielGil** [comment]
Just inject it in your app and on the closure.

``` js
app.module('yourMod', ['ngStorage']);
app.provider('item', function($localStorage) {});
```

**Comment by egilkh** [comment]
Can also be done with more explicit dependency injection

```javascript
app.module('yourMod', ['ngStorage']);
app.provider('item', ['$localStorage', function($localStorage) {}]);
```

**Comment by GabrielGil** [comment]
Just curiosity, what is the main advantage/difference of injecting it the way you proposed with an array @egilkh?

**Comment by egilkh** [comment]
Mainly I think it's useful for minify/uglify tasks that try to mangle your parameters. Another thing you can do is "alias" the name of the injection. Example:

```javascript
app.provider('item', ['$localStorage', function(ls) {}]);
```

Personally I like it more because it's just more verbose and there is no guesswork when reading the code.

For reference: https://docs.angularjs.org/guide/di

**Comment by GabrielGil** [comment]
Makes lot of sense. Thank you for the note and the reference. So useful.
