### ISSUE TITLE
npm install ng-storage is huge!

### ISSUE THREAD

**Issue by hughperkins** [gsklee/ngStorage#77]
`npm install ng-storage` installs all devdependencies, which is 50MB of files

please can you consider moving all the grunt and karma stuff and so on into devdepencies?

**Comment by sompylasar** [comment]
This repo is not maintained by the owner. Please find an alternative: angular-locker for example.

**Comment by hughperkins** [comment]
What do you mean by 'the owner'?  You mean, you are an onlooker, who monitors the issues in this project a bit, but you are not the owner, and neither your, nor the owner, are maintaining ng-storage?

**Comment by sompylasar** [comment]
Yes, you are right about me. I am looking after this project and guiding people to find an alternative because the owner is not responding anymore. I've used ngStorage for a single project and had to fix some annoying bugs to finish the project. I found later that the way ngStorage is built is not the best way. You'd better have a service for a storage layer, be it localStorage or a database, the architecture is the same. So I don't maintain ngStorage because there are better and more complete and maintained alternatives to do the same thing better way.

If you still not convinced and want to use ngStorage, you can do the necessary changes yourself. Just fork my fork, make changes you want, then install directly from the GitHub URL, not from the NPM registry. That's how I used my changes for my project.

**Comment by hughperkins** [comment]
Hmmm, ok.  ng-storage is easier to use, but if it's going to be buggy, then, fine, I already have a dozen or two repositories to my name, and don't want to spread myself too thinly...

For now, I will just do what I did in the end: just directly added ngStorage.min.js to my project, rather than adding it to project.json or bower.json.

**Comment by egilkh** [comment]
You can try using this https://www.npmjs.com/package/ngstorage it should not be a huge install unless you install dev dependencies.
