### ISSUE TITLE
Module 'ngStorage' is not available!

### ISSUE THREAD

**Issue by qpi** [gsklee/ngStorage#98]
I use requirejs in my project to load all the JS files and dependencies. Original I used version 0.3.0 without any problem. Today I upgraded to 0.3.4 and I receive this error while my app tries to bootstrap:

Error: [$injector:modulerr] Failed to instantiate module ngStorage due to:
Error: [$injector:nomod] Module 'ngStorage' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.

**Comment by iamaro** [comment]
im having the same issue

**Comment by Dathix** [comment]
Same here with 0.3.4 even bower is not able to resolve ngStorage.

**Comment by egilkh** [comment]
Due to some changes that was made in the UMD/CommonJS/RequireJS/<insert loading framework> code there is a slight problem with this. We are working on getting this resolved and should have a new release asap.

@Dathix the readme states : `bower install ngstorage` to install. Which should work. ngStorage is some other module.

**Comment by NitroInside** [comment]
Same here, the bower.json file has the right dependency... it works on 0.3.0 but fails in 0.3.4

**Comment by kevinvavelin** [comment]
Issue is still present with Ionic and ngstorage version 0.3.10

**Comment by Jaspur** [comment]
Re-open issue?

**Comment by hiep8024** [comment]
I fixed this problem with uninstall ngStorage and reinstall with bower install ngstorage
